[versions]
paper-api = "1.21-R0.1-SNAPSHOT"
lombok = "1.18.42"
placeholderapi = "2.11.7"
commandapi = "11.1.0"
shadow = "9.2.2"
run-paper = "3.0.2"

[libraries]
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper-api" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
placeholderapi = { group = "me.clip", name = "placeholderapi", version.ref = "placeholderapi" }
commandapi = { group = "dev.jorel", name = "commandapi-paper-shade", version.ref = "commandapi" }

[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }